name: Build

on:
  push:
    branches:
      - main

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build Android
        working-directory: frontend/android
        run: ./gradlew assembleRelease

      - name: Archive Android artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-release
          path: frontend/android/app/build/outputs/apk/release/*.apk

  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build iOS
        working-directory: frontend/ios
        run: |
          pod install
          xcodebuild -workspace frontend.xcworkspace -scheme frontend -configuration Release -archivePath build/frontend.xcarchive archive
          xcodebuild -exportArchive -archivePath build/frontend.xcarchive -exportPath build -exportOptionsPlist ExportOptions.plist

      - name: Archive iOS artifact
        uses: actions/upload-artifact@v2
        with:
          name: ios-release
          path: frontend/ios/build/*.ipa
